version: '3.5'

services:
  postgres-compose:
    image: postgres:15.3
    container_name: postgres
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=ps789
        - TZ=GMT
    volumes:
        - ./data/postgresql:/var/lib/postgresql/data
    ports:
        - "15432:5432"
  
  mongodb-compose:
    image: mongo:4.2
    container_name: mongo
    volumes:
        - ./data/mongodb:/data/db
    ports:
        - "27017:27017"